[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "cullen"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "typer",
    "rich",
    "justin_utils",
]
description = ""
readme = "README.md"
license = "MIT"
authors = [{name = "Igor Djachenko"}]

[project.scripts]
cullen = "cullen.main:app"

[project.optional-dependencies]
test = [
    "pytest",
]
release = ["build >= 1.5", "python-semantic-release >= 10.6"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src", "tests"]
testpaths = ["tests"]

[tool.semantic_release]
major_on_zero = false
version_toml = ["pyproject.toml:project.version"]
tag_format = "v{version}"
branch = "master"
commit_message = "chore(release): v{version} [skip ci]"
allow_zero_version = true

[project.urls]
Homepage = "https://github.com/djachenko/cullen-cli"
Source = "https://github.com/djachenko/cullen-cli"
Documentation = "https://github.com/djachenko/cullen-cli#readme"
Issues = "https://github.com/djachenko/cullen-cli/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/cullen-cli"]

[tool.mypy]
strict = true
