[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "cullen"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "typer",
]

[project.scripts]
cullen = "cullen.cullen:app"

[tool.setuptools.packages.find]
where = ["src"]

[tool.semantic_release]
major_on_zero = false
